---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-pv
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-rbd
  csi:
    driver: rbd.csi.ceph.com
    volumeHandle: immich-postgres
    volumeAttributes:
      clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
      pool: kubernetes
      staticVolume: "true"
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cephfs
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: immich-data
    volumeAttributes:
      clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
      staticVolume: "true"
      rootPath: /immich
      fsName: "cephfs"
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: ceph-csi-cephfs
