---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: vaultwarden-secrets
    template:
      type: Opaque
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: homelab/vaultwarden/app-secrets
        property: ADMIN_TOKEN
