---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-db-backup
  namespace: vaultwarden
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: vaultwarden-db
