---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nemmest-db
  namespace: nemmest
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  storage:
    size: 2Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: app
      owner: app

  postgresql:
    parameters:
      max_connections: "100"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: nemmest-db-backup

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
