---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nemmest-db-backup
  namespace: nemmest
spec:
  configuration:
    destinationPath: s3://cnpg-backups/nemmest-db/
    endpointURL: http://rustfs.rustfs:9000
    s3Credentials:
      accessKeyId:
        name: cnpg-aws-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-aws-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
      immediateCheckpoint: false
      jobs: 2
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  retentionPolicy: "7d"
