---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nemmest-db-backup-schedule
  namespace: nemmest
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: nemmest-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
