---
# AWS credentials for CNPG Barman Cloud backups.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-aws-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cnpg-aws-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: homelab/cnpg/aws-credentials
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: homelab/cnpg/aws-credentials
        property: ACCESS_SECRET_KEY
