---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-aws-credentials
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: cnpg-aws-credentials
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "resume,home-assistant"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "resume,home-assistant"
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: homelab/cnpg/aws-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: homelab/cnpg/aws-credentials
        property: AWS_SECRET_ACCESS_KEY