---
globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

log:
  level: DEBUG

traefik: 


  api: 
    insecure: true

  providers:
    kubernetesGateway:
      enabled: true
    kubernetesIngress:
      enabled: false

  gateway:
    namespacePolicy: All



  ingressClass:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  additionalArguments:
    # Disable read timeout to allow large video uploads (e.g. via immich-go)
    - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=0"
