---
traefik:
  global:
    sendAnonymousUsage: false
    checkNewVersion: false

  logs:
    general:
      level: DEBUG

  api:
    insecure: true

  service:
    spec:
      loadBalancerIP: ""

  providers:
    kubernetesGateway:
      enabled: true
    kubernetesIngress:
      enabled: false
    kubernetesCRD:
      enabled: false

  gateway:
    enabled: false

  ports:
    web:
      http:
        redirections: null

  ingressClass:
    enabled: false
    name: traefik

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  additionalArguments:
    # Disable read timeout to allow large video uploads (e.g. via immich-go)
    - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=0"
