---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: resume-db
  namespace: resume
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  storage:
    size: 5Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: app
      owner: app

  postgresql:
    parameters:
      max_connections: "100"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
