---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resume

resources:
  - namespace.yaml
  - rbac.yaml
  - dev/secrets.yaml
  - dev/rustfs-credentials.yaml
  - dev/object-store.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - database.yaml
  - scheduled-backup.yaml
