---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resume-secrets
  namespace: resume
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: resume-secrets
    template:
      type: Opaque
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: homelab/resume/app-secrets
        property: AUTH_SECRET
