---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resume

resources:
  - ../../base/namespace.yaml
  - ../../base/rbac.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/ingress.yaml
  - ../../base/database.yaml
  - ../../base/scheduled-backup.yaml

  - external-secret.yaml
  - object-store.yaml

patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml
