---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: resume-db-backup
  namespace: resume
spec:
  configuration:
    destinationPath: s3://homelab-cnpg-barman-backups/resume-db/
    endpointURL: ""
    s3Credentials:
      accessKeyId:
        name: cnpg-aws-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-aws-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
      immediateCheckpoint: false
      jobs: 2
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: eu-north-1
  retentionPolicy: "30d"
