---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-production-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: system-configs-production
            path: system/configs/production
            namespace: default
            wave: "-4"
          - name: monitoring-configs-production
            path: monitoring/configs/production
            namespace: monitoring
            wave: "-3"
          - name: apps-production
            path: apps/production
            namespace: default
            wave: "-2"
  template:
    metadata:
      name: "{{.name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
    spec:
      project: homelab
      source:
        repoURL: https://github.com/skjoedt/homelab.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
