---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - system-controller-apps.yaml
  - system-kustomize-apps.yaml
  - monitoring-controller-apps.yaml
  - environment-apps.yaml
