---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-monitoring-controllers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/skjoedt/homelab.git
        revision: main
        directories:
          - path: monitoring/controllers/*
  template:
    metadata:
      name: "{{.path.basename}}"
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      project: homelab
      source:
        repoURL: https://github.com/skjoedt/homelab.git
        targetRevision: main
        path: "{{.path.path}}"
        helm:
          releaseName: "{{.path.basename}}"
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
