---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arm-omdb-api-key
  namespace: arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: arm-omdb-api-key
    template:
      type: Opaque
  data:
    - secretKey: omdb_api_key
      remoteRef:
        key: homelab/omdb/api-key
        property: api_key
