apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbootxyz
resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: netbootxyz-nginx-config
    files:
      - default=configs/nginx-site.conf
    options:
      disableNameSuffixHash: true
