---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config-pvc
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-assets-pvc
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
