---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - credentials.yaml
  - storageclass.yaml
  - ingress-ceph.yaml
  - volumesnapshotclass-rbd.yaml
  - volumesnapshotclass-cephfs.yaml
