---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foundry-secrets
  namespace: foundry
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: foundry-secrets
    template:
      type: Opaque
  data:
    - secretKey: FOUNDRY_PASSWORD
      remoteRef:
        key: homelab/foundry/app-secrets
        property: FOUNDRY_PASSWORD
    - secretKey: FOUNDRY_ADMIN_KEY
      remoteRef:
        key: homelab/foundry/app-secrets
        property: FOUNDRY_ADMIN_KEY
