---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
  namespace: foundry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
