---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: musicseerr-route
  namespace: musicseerr
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - musicseerr.localho.st
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: musicseerr
          port: 8688
