---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: homeassistant-db-secret-reader
  namespace: home-assistant
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homeassistant-db-secret-reader
  namespace: home-assistant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homeassistant-db-secret-reader
subjects:
  - kind: ServiceAccount
    name: homeassistant-db
    namespace: home-assistant
