#cloud-config
users:
  - name: skjoedt
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, sudo
    shell: /bin/zsh
    ssh_import_id:
      - gh:skjoedt
    lock_passwd: true

package_update: true
packages:
  - git
  - ntp
  - zsh

runcmd:
  - echo 'fs.inotify.max_user_instances=512' >> /etc/sysctl.conf
  - echo 'fs.inotify.max_user_watches=524288' >> /etc/sysctl.conf
  - sysctl -p
