---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-aws-credentials
  namespace: velero
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: velero-aws-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .AWS_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .AWS_SECRET_ACCESS_KEY }}
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: homelab/velero/aws-credentials
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: homelab/velero/aws-credentials
      property: AWS_SECRET_ACCESS_KEY