---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  template:
    spec:
      initContainers:
      - name: config-init
        image: alpine:3.19
        command: # gettext package contains envsubst
          - sh
          - -c
          - |
            apk add --no-cache gettext
            envsubst < /config-template/AdGuardHome.yaml > /config/AdGuardHome.yaml
        env:
        - name: ADGUARD_USER
          valueFrom:
            secretKeyRef:
              name: adguard-home-credentials
              key: user
        - name: ADGUARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguard-home-credentials
              key: password
        volumeMounts:
        - name: config-template
          mountPath: /config-template
        - name: config-processed
          mountPath: /config
      containers:
      - name: adguard-home
        volumeMounts:
        - name: adguard-data
          mountPath: /opt/adguardhome/work
          subPath: work
        - name: config-processed
          mountPath: /opt/adguardhome/conf
          subPath:
      volumes:
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-home-data-pvc
      - name: config-template
        configMap:
          name: adguard-home-config
      - name: config-processed
        emptyDir: {}
      - name: adguard-config
        $patch: delete