---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-home-credentials
  namespace: adguard-home
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: adguard-home-credentials
    template:
      type: Opaque
  data:
    - secretKey: user
      remoteRef:
        key: homelab/adguard-home/credentials
        property: user
    - secretKey: password
      remoteRef:
        key: homelab/adguard-home/credentials
        property: password