---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard-home

resources:
  - ../../base/adguard-home
  - pv.yaml

patches:
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - path: pvc-config-patch.yaml
  - path: pvc-data-patch.yaml