---
- Popular:
    - Jellyfin:
        href: https://jellyfin.fanen.dk
        description: Media system (movies, music, etc.)
        icon: jellyfin.svg
    - Seerr:
        href: https://seerr.fanen.dk
        description: Request management for media
        icon: seerr.svg
    - Photos:
        href: https://photos.fanen.dk
        description: Photo album
        icon: immich.svg
    - Budget:
        href: https://budget.fanen.dk
        description: Personal finance
        icon: actual-budget.svg
- Tools:
    - Resume:
        href: https://resume.fanen.dk
        description: Personal resume
        icon: reactive-resume.svg     
- Management:
    - Arm:
        href: https://arm.fanen.dk
        description: Ripping of physical media
        icon: arm.svg
    - Qbittorrent:
        href: https://qbittorrent.fanen.dk
        description: Bittorrent client
        icon: qbittorrent.svg
    - Prowlarr:
        href: https://prowlarr.fanen.dk
        description: Indexer management
        icon: prowlarr.svg
    - Radarr:
        href: https://radarr.fanen.dk
        description: Movie tracker
        icon: radarr.svg
    - Sonarr:
        href: https://sonarr.fanen.dk
        description: TV show tracker
        icon: sonarr.svg
    - AdGuard Home:
        href: https://adguard.fanen.dk
        description: Network-wide adblocker
        icon: adguard-home.svg  
- Monitoring:
    - Grafana:
        href: https://grafana.fanen.dk
        description: Observability dashboards
        icon: grafana.svg
    - Alloy:
        href: https://alloy.fanen.dk
        description: Logging dashboard
        icon: alloy.svg
    - Alerts:
        href: https://alerts.fanen.dk
        description: Alert Managers
        icon: alertmanager.svg
