---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
