---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cephfs
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: jellyfin-data
    volumeAttributes:
      clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
      pool: kubernetes-staging
      staticVolume: "true"
      rootPath: /volumes/jellyfin
      fsName: "cephfs"
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: ceph-csi-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: cephfs
  volumeName: jellyfin-data-pv
