---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
  namespace: arr
spec:
  csi:
    volumeAttributes:
      clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
      pool: kubernetes
