---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-pvc
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: cephfs
