---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  template:
    spec:
      containers:
        - name: gluetun
          env:
            - name: DNS_UPSTREAM_RESOLVER_TYPE
              value: "plain"
            - name: DNS_UPSTREAM_PLAIN_ADDRESSES
              value: "10.43.0.10:53"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/16,10.43.0.0/16"
      securityContext:
        fsGroup: 501
        fsGroupChangePolicy: "OnRootMismatch"
        sysctls:
          - name: net.ipv4.conf.all.rp_filter
            value: "2"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "1"
