---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dozzle-users
  namespace: dozzle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: dozzle-users
    template:
      type: Opaque
  data:
    - secretKey: users.yml
      remoteRef:
        key: homelab/dozzle/users
