---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-viewer
  namespace: dozzle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle-pod-viewer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle-pod-viewer-binding
subjects:
  - kind: ServiceAccount
    name: pod-viewer
    namespace: dozzle
roleRef:
  kind: ClusterRole
  name: dozzle-pod-viewer-role
  apiGroup: rbac.authorization.k8s.io
