---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qui
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - &host qui.fanen.dk
      secretName: qui-fanen-dk-tls
  rules:
    - host: *host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qui
                port:
                  name: http
