---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage
  - actual
  - adguard-home
  - jellyfin
  - seerr
  - prowlarr
  - qbittorrent
  - qui
  - radarr
  - sonarr
  - bazarr
  - arm
  - resume-dev
  - papra
  - home-assistant-dev
