---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage
  - actual
  - adguard-home
  - jellyfin
  - seerr
  - prowlarr
  - qbittorrent
  - radarr
  - sonarr
  - arm
