---
cert-manager:
  crds:
    enabled: true

  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    enableGatewayAPI: true

  dns01RecursiveNameservers: "1.1.1.1:53,9.9.9.9:53"
  dns01RecursiveNameserversOnly: true
  podDnsPolicy: None
  podDnsConfig:
    nameservers:
      - 1.1.1.1
      - 9.9.9.9

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
