---
image:
  repository: ghcr.io/kube-vip/kube-vip
  tag: "v0.5.12"

env:
  vip_interface: "eth0"

config:
  vip_address: "10.0.0.10"
  port: 6443
  vip_interface: "eth0"
  cp_enable: true
  serviceEnable: true # Enable service handling
  services_enable: true
  address_range: "10.0.0.50-10.0.0.100" # Range for LoadBalancer services