---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra-secrets
  namespace: papra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: papra-secrets
    template:
      type: Opaque
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: homelab/papra/app-secrets
        property: AUTH_SECRET
