---
apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: hermes-personal
spec:
  selector:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/instance: hermes-personal
  ports:
    - name: gateway
      protocol: TCP
      port: 8642
      targetPort: gateway
    - name: dashboard
      protocol: TCP
      port: 9119
      targetPort: dashboard
