---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
  namespace: foundry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cephfs
